name: Build Chocolatey Package

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Chocolatey Natively
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          echo "$env:ProgramData\chocolatey\bin" >> $env:GITHUB_PATH

      - name: Build NUPKG Package Dynamically
        shell: pwsh
        run: |
          $zipAsset = Get-ChildItem -Filter *.zip | Select-Object -First 1
          if (-not $zipAsset) {
              throw "No se encontró ningún archivo .zip."
          }

          $baseName = $zipAsset.BaseName
          $parts = $baseName -split '-'   
          $marca = $parts[1]          
          $modelo = $parts[2]         

          $nuspecContent = Get-Content -Path "template.nuspec" -Raw
          $nuspecContent = $nuspecContent -replace '\$MARCA\$', $marca
          $nuspecContent = $nuspecContent -replace '\$MODELO\$', $modelo
          
          $finalNuspecName = "reset-$marca-$modelo.nuspec"
          Set-Content -Path $finalNuspecName -Value $nuspecContent

          choco pack $finalNuspecName

      - name: Upload NUPKG to Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: '*.nupkg'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
